name : CI/CD 

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]
  
jobs:       
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout FIRST
      - name: Checkout code 
        uses: actions/checkout@v3
        
      # 2. Set up python
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. Clone external repo
      - name: Clone external repo
        run: |
          git clone https://github.com/microsoft/recommenders.git src/steps/stage_03_model_trainer/recommenders_microsoft

      # 4. Install recommenders
      - name: Install recommenders
        run: pip install -e src/steps/stage_03_model_trainer/recommenders_microsoft

      # 5. Set PYTHONPATH
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      # 6. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 7. Run tests
      - name: Run tests
        run: pytest tests/
        
  build-and-publish:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps : 
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v2 

    - name: Login to DockerHub 
      uses: docker/login-action@v2 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file : ./Dockerfile
        push : true
        tags: ${{ secrets.DOCKER_USERNAME }} / BookRecommenderSystem-app:latest
    - name: Image digest
      run: echo ${{ steps.build-and-publish.outputs.digest }}  
        
